### ISSUE TITLE
Database encoding is set to SQL_ASCII

### ISSUE THREAD

**Issue by treyhyde** [orchardup/docker-postgresql#13]
The dockerfile lists initdb params of UTF-8 but the databases that ship by default with this image are all SQL_ASCII.

 \l
                             List of databases
   Name    |  Owner   | Encoding  | Collate | Ctype |   Access privileges  
-----------+----------+-----------+---------+-------+-----------------------
 docker    | docker   | SQL_ASCII | C       | C     | 
 postgres  | postgres | SQL_ASCII | C       | C     | 
 template0 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
           |          |           |         |       | postgres=CTc/postgres
 template1 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
           |          |           |         |       | postgres=CTc/postgres
(4 rows)

**Comment by aanand** [comment]
I can reproduce this on master, but not on the `9.1` branch:

```
$ git checkout -b 9.1 origin/9.1
$ docker build -t postgresql .
$ docker run -d --name db postgresql
$ docker run --link db:db -i -t postgresql psql -h db -U docker -c '\l'
Password for user docker:
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 docker    | docker   | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)
```

Looks like this regression was caused by #8 - could be an Ubuntu 14.04 thing. Investigating.
