### ISSUE TITLE
could not open file "/var/lib/postgresql/9.1/main/PG_VERSION": Permission denied

### ISSUE THREAD

**Issue by 1xch** [orchardup/docker-postgresql#5]
I recently installed Ubuntu 14.04, using Docker version 1.0.1, build 990021a

I had an existing installation(Ubuntu 13.10); reusing the same location for data storage, but now I get when trying to start the container:

2014-06-26 17:20:59 UTC FATAL:  could not open file "/var/lib/postgresql/9.1/main/PG_VERSION": Permission denied

I have postgresql 9.3 installed systemwide from the repositories there is no 9.1; which should not matter.

**Comment by 1xch** [comment]
I tried forking and updating to a new build with 14.04/postgresql 9.3, but the message persists.

2014-06-26 18:13:00 UTC FATAL:  could not open file "/var/lib/postgresql/9.3/main/PG_VERSION": Permission denied

https://github.com/thrisp/docker-postgresql

**Comment by 1xch** [comment]
The issue is within the use of -v flag:

```
sudo docker run -d -p 127.0.0.1:5432:5432 -v /local:/var/lib/postgresql orchardup/postgresql
```

Where /local is a drive I have data on; not sure why the permission trouble there specifically and nowhere else but other than that the problem is mine.

**Comment by johnjelinek** [comment]
I noticed the same thing when copying my volume. I ended up needing to `cp -rp posgres postgres-backup` and then the permissions worked.
