### ISSUE TITLE
Unable to run example from readme

### ISSUE THREAD

**Issue by jscottmiller** [orchardup/docker-postgresql#9]
I am running this image using in fresh, ubuntu 14.04, Vagrant-managed vm running the docker 1.1 (installed from the official docker deb repo).

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-30-generic #54-Ubuntu SMP Mon Jun 9 22:45:01 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ docker -v
Docker version 1.1.1, build bd609d2
```

I am running this image using fig. I build the and tag the image with fig build, not using docker directly. The issue comes when I try to run the example given in the repo's readme:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ docker run -d -p 5432:5432 -e POSTGRESQL_USER=test -e POSTGRESQL_PASS=oe9jaacZLbR9pN -e POSTGRESQL_DB=test orchardup/postgresql
96184caf3879435db6fe15b8eb0e671f202acfd922571671fc04a040b9593814
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ docker ps
CONTAINER ID        IMAGE                         COMMAND              CREATED             STATUS              PORTS                    NAMES
96184caf3879        orchardup/postgresql:latest   /usr/local/bin/run   5 seconds ago       Up 3 seconds        0.0.0.0:5432->5432/tcp   hopeful_fermi       
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ psql -h localhost -U test test
psql: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

The postgres container appears to be running and listening on the correct port. The port appears to be forwarded correctly on the host:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ netstat -a
....
tcp6       0      0 [::]:postgresql         [::]:*                  LISTEN
....
```

The connection isn't refused - it's being immediately closed by the postgres instance. My best guess is that this is an authentication problem, but I'm not sure how to diagnose it. (My apologies, I'm new to postgres admin.) I'm not running into any issues with other fig-managed containers (my app and orchardup/docker-redis).

Let me know if you need more info. I'll keep looking into this on my end.

**Comment by jscottmiller** [comment]
Ran the image with log level set to debug5 and yet connection requests didn't go through. Ran postgres AND psql from within the contain and the client was able to connect. Looked at the config and noticed this:

```
#listen_addresses = '*'     # what IP address(es) to listen on;
```

I don't know the details of docker's mechanics, but I suspect that it needs to listen on the docker interface (172.17.x.x). If that's the case, a quick solution would be to uncomment this line.

**Comment by bfirsh** [comment]
Looks like this was broken here https://github.com/orchardup/docker-postgresql/pull/8/files#diff-ee6497e8a17df7eb3e450615b089b0f4L59
